### ISSUE TITLE
EXC_BAD_ACCESS in [IntelHex2BinConverter convert]

### ISSUE THREAD

**Issue by bisikli** [nordicsemi/IOS-DFU-Library#156]
Hello, 

I am having the following crash during a dfu. Could you please have a look? 

Thanks. 

<img width="1280" alt="27959439-17c78b6e-6330-11e7-97df-7f650d56d38a" src="https://user-images.githubusercontent.com/16748312/32090404-e7d1bb26-baf7-11e7-92f6-b985fd1b668f.png">

**Comment by philips77** [comment]
Are you sure your hex file is correct? Seems like its size is 0 or is not a hex file. Put a breakpoint in that line and check the calculated sizes and why the loop didn't break before crashing. Could you send us the file if it looks ok?
Also, we recommend using the distribution packets (Zip files) instead of hex+dat file.

**Comment by bisikli** [comment]
Closing this thread for now as i am not sure about the hex file and will try to test with a zip version. 

Thank you!

**Comment by mostafaberg** [comment]
Ok keep us updated, If you still have issues just let us know
