### ISSUE TITLE
203 Could not obtain peripheral instance

### ISSUE THREAD

**Issue by rajtharan-g** [nordicsemi/IOS-DFU-Library#256]
Currently, we are starting the DFU process as follows,

 ```
        let dfuInitiator = DFUServiceInitiator(queue: DispatchQueue(label: "DFUQueue"))
        dfuInitiator.delegate = self
        dfuInitiator.progressDelegate = self
        dfuInitiator.logger = self
        if #available(iOS 11.0, *) {
            dfuInitiator.packetReceiptNotificationParameter = 0
        }
        dfuController = dfuInitiator.with(firmware: firmware).start(target: dfuPeripheral)
```

And we get the error 203 which is trigged by following code from the library
       `delegate?.dfuError(.bluetoothDisabled, didOccurWithMessage: "Could not obtain peripheral instance")`

Once the peripherals found in DFUTarg, we  connect to the device and keep a strong reference to it in singleton class. The dfuPeripheral that is being passed is taken from the singleton class and is not nil. Then we start the DFU process, however we get 203 error for some users. Any help regarding which may cause this issue is highly appreciated. This issue was noted in iPhone 8, iOS 11.4.1 .

**Comment by philips77** [comment]
How often does it happen? Is it easy for you to reproduce?
The only possible reason that I can see is that the CBCentralManager instance created in init(queue) is not ready yet. Could you wait a bit before calling start? When the state changes to .on, will this work? (I know you don;t want to know exactly when it will change to .on, but you may add some delay). If it's required, I'll implement waiting for state change in the lib.

**Comment by philips77** [comment]
Yes, so usually it works. When there is an issue with the phone (?) or someone plays with Bluetooth by turning it off and on (?) things may be unpredictable.
If the issue is not reproducible on your side, I would recommend just handling the exception in your code. It may be a temporary issue with the phone, perhaps restarting Bluetooth in settings would help? I don't think anything else can be done if the Bluetooth adapter is not stable.
Waiting 1 sec for all users seems to have no sense, also it may not help in this situation. I only meant testing if the issue was reproducible. 

By modifying the lib I had in mind waiting for .on state before retrieving the device, not only before connecting to it. Currently the lib waits here: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/GenericDFU/DFUPeripheral.swift#L106 and resumes here: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/GenericDFU/DFUPeripheral.swift#L189 when state is .poweredOn.

**Comment by osawhoop** [comment]
I was able to reproduce this issue using an iPhone X with iOS 13, they way I fix it is just adding a 5 seconds delay before to call initiator.start()
```swift
let queueStartDFU = DispatchQueue(label: "DFUController")
        queueStartDFU.asyncAfter(deadline: .now() + gDFUDelayStart) {
self.dfuController = dfuInitiator.with(firmware: firmware).start(target: selectedPeripheral)
        }
```

**Comment by Hellogz** [comment]
> I was able to reproduce this issue using an iPhone X with iOS 13, they way I fix it is just adding a 5 seconds delay before to call initiator.start()
> 
> ```swift
> let queueStartDFU = DispatchQueue(label: "DFUController")
>         queueStartDFU.asyncAfter(deadline: .now() + gDFUDelayStart) {
> self.dfuController = dfuInitiator.with(firmware: firmware).start(target: selectedPeripheral)
>         }
> ```

iOS 13 iPhone XR me too.

**Comment by philips77** [comment]
I'll look into it when I start testing with iOS 13. I understand that this is important and should start doing this soon. For now try the workaround suggested above.

**Comment by philips77** [comment]
This should be working now with version 4.5.1.

**Comment by padishahG** [comment]
Why do I still have 4.4 after pod search iOSDFULibrary?

**Comment by philips77** [comment]
You need to update Cocoa Pods on your Mac.

**Comment by padishahG** [comment]
thank you
