### ISSUE TITLE
Xcode 12 and maybe new requiriment

### ISSUE THREAD

**Issue by Lucasark** [nordicsemi/IOS-DFU-Library#390]
**DFU Bootloader version (please complete the following information):**
 - SDK version: [e.g. SDK 16]
 - Bonding used: [yes/no]
 - Library version: 4.9.0

**Device information (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 13

**Describe the bug**
After upgrade my Xcode to 12.1 (not Beta) I got this error:
```
'DFUFirmware' with definition in module 'iOSDFULibrary.Swift' has different definitions in different modules; first difference is this method
'DFUFirmwareSize' has different definitions in different modules; first difference is definition in module 'iOSDFULibrary.Swift' found 3
'DFUServiceController' with definition in module 'iOSDFULibrary.Swift' has different definitions in different modules; first difference is this method
'DFUServiceInitiator' has different definitions in different modules; first difference is definition in module 'iOSDFULibrary.Swift' found property name 'forceScanningForNewAddressInLegacyDfu'
```
I already update my pod to 4.9.0 to catch last PR that mention Xcode 12. 

![image](https://user-images.githubusercontent.com/31750882/98436473-55c65800-20ba-11eb-8cdf-ba7cd074d25a.png)

Temporary Workaround:
Downgrade to 4.8.0 and using Xcode 11.7

In this link mention that:
> This problem occurs after XCode 12 Beta5. Xcode doesn't allow different modules to define same names (Probably for public classes & protocols). Alamofire and Kingfisher appears to define SessionDelegate at the same time. I'm still trying to find a solution..

https://stackoverflow.com/questions/63614048/xcode-12-sessiondelegate-has-different-definitions-in-different-modules

**Logs**
Add any other context or logs describing the problem here.

![image](https://user-images.githubusercontent.com/31750882/98436427-d89ae300-20b9-11eb-9fba-c883ab568e15.png)

**Comment by octalanil1** [comment]
![Screenshot 2020-12-09 at 12 50 33 PM](https://user-images.githubusercontent.com/53342174/101597833-428e0b80-3a1d-11eb-86cb-d0ff929c0ee1.png)
![Screenshot 2020-12-09 at 12 51 11 PM](https://user-images.githubusercontent.com/53342174/101597845-4752bf80-3a1d-11eb-9c6e-2aa22fa12518.png)

I'm also facing same error in xcode 12.1.
If you find any solution please let me know ASAP.

**Comment by jsimonassi** [comment]
This problem happened to me because iOSDFULibrary had the same class / method name as IDOBluetooth (A .framework also used in my project). I managed to build with a few steps:

1 - Search for the conflicting class / method by filtering through the iOSDFULibrary folder inside your Pods folder;
![Captura de Tela 2020-12-09 às 11 01 27](https://user-images.githubusercontent.com/33124078/101641929-23897c80-3a11-11eb-9240-9c288a4a6f6c.png)

2 - Rename all occurrences. (In my case, I renamed DFUFirmware to DFUFirmwareBle);

3 - Try to build. At this point I received this error:
![Captura de Tela 2020-12-09 às 11 15 11](https://user-images.githubusercontent.com/33124078/101642782-26d13800-3a12-11eb-90ad-b19f2a18d26c.png)

I solved it with a cmd + k.

4 - Rename all calls within your project that use the iOSDFUFirmware methods / classes. XCode will help you with this part by showing the errors.

At this point, the build was done successfully for me.

**Comment by octalanil1** [comment]
No it's not working.
If saw screenshoot it's clearly showing my problem is in DFUServiceInitiator class and DFUServiceDelegate.
So any othe solution please let me know asap, i stuck in this pb from last two days.

**Comment by Lucasark** [comment]
> No it's not working.
> If saw screenshoot it's clearly showing my problem is in DFUServiceInitiator class and DFUServiceDelegate.
> So any othe solution please let me know asap, i stuck in this pb from last two days.

@octalanil1 My problem is not same is yours. 
Your error is more like to using same name of class in differents files of your project.
I recommend you print your log error. Or, maybe ready carefully.

I work with @jsimonassi to solve this.  And, have sucess. So, i am closing this issue.
But, make a alert for who is using more than one SDK that use iOSDFU.
