### ISSUE TITLE
Issue while discovering services

### ISSUE THREAD

**Issue by silicusaditi** [nordicsemi/IOS-DFU-Library#406]
We used NRF application to check our device. The application connects to the device but automatically disconnects after 30 seconds. During this timeframe it displays the advertised services.
We tried the same using code. The application connects to the device but automatically disconnects after 30 seconds. Here it does not display any services. Can you please explain if there is any difference between code and application.

**Comment by philips77** [comment]
> We used NRF application to check our device. 

What is NRF application? I guess you are talking about nRF Connect for iOS. Why creating the issue in DFU library then?

> The application connects to the device but automatically disconnects after 30 seconds.

This may be related to unsupported connection interval, when the device does not agree to one chosen by iOS. Or some other reason, like intentional disconnection.

> During this timeframe it displays the advertised services.

Are you talking about GATT services aka attribute table (services, characteristics, descriptors), not advertising data? A device advertises usually if it's not connected, then stops advertising when connected (in some use cases it continue to advertise). Advertised services would be the services the device has advertised with using Service UUID field in the advertising packet. They don't have to match the attribute table, so you may advertise with different services, that a device in fact has in its table. Not smart, but possible, as they are independent.

> Here it does not display any services.

So you cannot to service discovery? The "Advertising services" you're talking about, visible in nRF Connect for iOS, are taken from advertising data using this callback: https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/1518937-centralmanager

> Can you please explain if there is any difference between code and application.

What code? What application?

**Comment by philips77** [comment]
Closing the issue due to inactivity.
